//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ermolaev.Classes
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ErmolaevEntities : DbContext
    {
        private static ErmolaevEntities _context;
        public ErmolaevEntities()
            : base("name=ErmolaevEntities")
        {
        }

        public static ErmolaevEntities GetContext()
        {
            if (_context == null)
            {
                _context = new ErmolaevEntities();
            }
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Postavki> Postavki { get; set; }
        public virtual DbSet<Selskoe_predpriyatie> Selskoe_predpriyatie { get; set; }
        public virtual DbSet<Produktsiya> Produktsiya { get; set; }
    }
}
