//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ermolaev.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Postavki
    {
        public int id_postavki { get; set; }
        public Nullable<System.DateTime> data_postavki { get; set; }
        public Nullable<int> obem { get; set; }
        public string sebestoimost { get; set; }
        public Nullable<int> id_predpriyatiya { get; set; }
        public Nullable<int> id_produkta { get; set; }
        public string photo { get; set; }
    
        public virtual Selskoe_predpriyatie Selskoe_predpriyatie { get; set; }
        public virtual Produktsiya Produktsiya { get; set; }
    }
}
